# Generated by Django 2.0.3 on 2018-10-28 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_manual_review', models.BooleanField(verbose_name='有流程')),
                ('role', models.CharField(choices=[('developer_supremo', '总监'), ('developer_manager', '经理'), ('developer', '研发')], max_length=32)),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8)),
                ('reject', models.BooleanField()),
                ('execute', models.BooleanField()),
                ('rollback', models.BooleanField()),
                ('approve', models.BooleanField()),
                ('disapprove', models.BooleanField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dbconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=5)),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8)),
                ('related_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('forbidden_words', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inceptsql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_manual_review', models.BooleanField(default=False, verbose_name='有流程')),
                ('commiter', models.CharField(blank=True, max_length=32, null=True)),
                ('sql_content', models.TextField()),
                ('sql_backup', models.TextField()),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('treater', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(-3, '已回滚'), (-2, '已暂停'), (-1, '待执行'), (0, '执行成功'), (1, '已放弃'), (2, '执行失败')], default=-1)),
                ('execute_errors', models.TextField(blank=True, default='', null=True)),
                ('exe_affected_rows', models.CharField(blank=True, max_length=10, null=True)),
                ('roll_affected_rows', models.CharField(blank=True, max_length=10, null=True)),
                ('rollback_opid', models.TextField(blank=True, null=True)),
                ('rollback_db', models.CharField(blank=True, max_length=100, null=True)),
                ('handle_result', models.TextField(blank=True, default='', null=True, verbose_name='处理详情')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Dbconf')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkOrder')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_manual_review', models.BooleanField(default=False, verbose_name='有流程')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Inceptsql')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='dbconf',
            unique_together={('name', 'host', 'env')},
        ),
    ]
