# Generated by Django 2.0.3 on 2018-10-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptsql',
            name='up',
            field=models.BooleanField(default=False, verbose_name='副总审批'),
        ),
    ]
