# Generated by Django 2.1.2 on 2018-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptsql',
            name='business_segments',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inceptsql',
            name='status',
            field=models.IntegerField(choices=[(-3, '已回滚'), (-2, '已暂停'), (-1, '待执行'), (0, '执行成功'), (1, '撤销'), (2, '执行失败'), (3, '执行成功，但回滚时效超过。')], default=-1),
        ),
    ]
