# Generated by Django 2.1.2 on 2018-11-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptsql',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Dbconf'),
        ),
    ]
