# Generated by Django 2.1.2 on 2018-10-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181025_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptsql',
            name='sql_backup',
            field=models.TextField(default='no sql'),
            preserve_default=False,
        ),
    ]
